helmDefaults:
  atomic: true
  wait: true

repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io
  - name: dex
    url: https://charts.dexidp.io
  - name: skm
    url: https://charts.sagikazarmark.dev
  - name: stable
    url: https://charts.helm.sh/stable

releases:
  - name: ingress-nginx
    namespace: ingress-nginx
    createNamespace: true
    chart: ingress-nginx/ingress-nginx
    version: 4.5.2
    missingFileHandler: Warn
    values:
      - apps/ingress-nginx/values.yaml
    wait: true
    waitForJobs: true

  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    version: v1.11.0
    missingFileHandler: Warn
    values:
      - apps/cert-manager/values.yaml
    installed: true
    wait: true
    waitForJobs: true

  - name: zerossl-issuer
    chart: apps/zerossl-issuer
    installed: true
    disableValidation: true
    values:
      - readenv.yaml.gotmpl

  - name: dex
    namespace: dex
    createNamespace: true
    chart: dex/dex
    version: 0.13.0
    missingFileHandler: Warn
    values:
      - apps/dex/values.yaml.gotmpl

  - name: dex-k8s-authenticator
    namespace: dex
    createNamespace: true
    chart: skm/dex-k8s-authenticator
    version: 0.0.2
    missingFileHandler: Warn
    values:
      - apps/dex-k8s-authenticator/values.yaml.gotmpl

  - name: kube-oidc-proxy
    namespace: kube-oidc-proxy
    createNamespace: true
    chart: src/kube-oidc-proxy/deploy/charts/kube-oidc-proxy
    missingFileHandler: Warn
    values:
      - apps/kube-oidc-proxy/values.yaml.gotmpl