apiVersion: v1
kind: Secret
metadata:
  annotations:
    app.kubernetes.io/instance: {{ .Values.CLUSTER_FQDN }}
    app.kubernetes.io/managed-by: {{ .Values.ZEROSSL_EMAIL }}
  namespace: cert-manager # Must be the namespace cert-manager is installed in
  name: zerossl-eab
stringData:
  secret: {{ .Values.ZEROSSL_EAB }}
